{"name": "Проверка невозможности логина при передаче в принципе несуществующей пары данных логин-пароль", "status": "passed", "description": "Передаем юзера, которого нет. Ожидаем фейл", "steps": [{"name": "Залогиниться под курьером", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'UniqueValue109', 'password': 'UniqueValue198'}"}], "start": 1721988970766, "stop": 1721988970841}], "start": 1721988970766, "stop": 1721988970842, "uuid": "faa1265f-a51f-446c-ac32-fae486c69ada", "historyId": "b2a4ebf2d2cb17b96e8b1e0221df0704", "testCaseId": "b2a4ebf2d2cb17b96e8b1e0221df0704", "fullName": "tests.test_login_courier.TestCourierLoginAPI#test_courier_login_nonexistant_courier_failure", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestCourierLoginAPI"}, {"name": "host", "value": "SlyPC"}, {"name": "thread", "value": "34324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}